/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package software.vistas;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import software.controladores.ConexionCOM;
import software.controladores.ControladorAdministracion;
import software.controladores.ControladorAprietes;
import software.controladores.ReportesPDF;
import software.controladores.confAplicacion;
import software.modelos.CamposActualizar;
import software.modelos.Usuario;

/**
 *
 * @author MSI
 */
public class Contenedor extends javax.swing.JFrame {

    /**
     * Creates new form Contenedor
     */
    private ControladorAdministracion contAdmin = new ControladorAdministracion();
    private ControladorAprietes contAprietes = new ControladorAprietes();
    private CamposActualizar campActualizar = new CamposActualizar();
    private ReportesPDF reportePDF = new ReportesPDF();
    private ConexionCOM conCOM;
    private confAplicacion confApp;

    public Contenedor() {
        initComponents();
    }

    public Contenedor(confAplicacion confApp) {
        initComponents();
        this.confApp = confApp;
        this.confApp.cargarFrameActivo(this);
        this.confApp.cargarTituloAplicacionContenedor();
        this.confApp.setContenedorPaneles((CardLayout) panelPrincipal.getLayout());
        this.confApp.activarAtajosTeclado();
        this.confApp.validarOperadorAdministrador(mAdmin);
        this.confApp.setHerramientas(this.contAdmin.cargarTablaHerramientas(tblAdminHerramientas));
        this.confApp.setPatrones(this.contAdmin.cargarPatrones(tblAdminPatrones));
        ArrayList<Usuario> listaOperadores = this.contAdmin.cargarTablaOperadores(tblAdminOperadores);
        if (listaOperadores != null && !listaOperadores.isEmpty()) {
            this.confApp.setListaOperadores(listaOperadores);
        }

        this.contAdmin.cargarModeloTablaAprietes(tblHerrAprietes);

        this.contAprietes.cargarHerramientas(cmbAprietesHerramientas, this.confApp.getHerramientas());
        this.contAprietes.cargarHerramientas(cmbAprieteHerramietasConsulta, this.confApp.getHerramientas());
        this.contAprietes.cargarPatrones(cmbAprietesPatron, this.confApp.getPatrones());

        this.conCOM = new ConexionCOM(mItemPuertosCom);
        this.conCOM.inicarBuscadorDePuertos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelPrincipal = new javax.swing.JPanel();
        scPanInicioApriete = new javax.swing.JScrollPane();
        panInicioApriete = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnAprietesIniciar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txfAprietesFechaHora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txfAprietesLinea1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txfAprietesODT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txfAprietesCliente = new javax.swing.JTextField();
        btnAprieteListarClientes = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cmbAprietesHerramientas = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        txfAprietesDireccion = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        cmbAprietesPatron = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        txfAprietesSerie = new javax.swing.JTextField();
        pnAprietesGrafica = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAprietesAprietes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        scPanInicioConsulta = new javax.swing.JScrollPane();
        panInicioConsulta = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txfAprieteODTConsulta = new javax.swing.JTextField();
        cmbAprieteClienteConsulta = new javax.swing.JComboBox<>();
        cmbAprieteHerramietasConsulta = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblAprietesConsulta = new javax.swing.JTable();
        btnAprietesIniciar1 = new javax.swing.JButton();
        scPanAdminOperador = new javax.swing.JScrollPane();
        panAdminOperador = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnOpGuardar = new javax.swing.JButton();
        btnOpNuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txfOpUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txfOpClave = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txfOpConfClave = new javax.swing.JPasswordField();
        txfOpCodigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txfOpNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txfOpApellido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txfOpDocumento = new javax.swing.JTextField();
        chkOpAdmin = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAdminOperadores = new javax.swing.JTable();
        scPanAdminHerramienta = new javax.swing.JScrollPane();
        panAdminHerramienta = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnOpNuevo2 = new javax.swing.JButton();
        btnOpGuardar2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txfHerrNombre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txfHerrSerial = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txfHerrMedida = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txfHerrDiasFuera = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txfHerrDistrict = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cmbHerrTpoReporte = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHerrAprietes = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAdminHerramientas = new javax.swing.JTable();
        lbHerrCodigo = new javax.swing.JLabel();
        scPanAdminPatron = new javax.swing.JScrollPane();
        panAdminPatron = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        btnOpNuevo1 = new javax.swing.JButton();
        btnOpGuardar1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txPatronNombre = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txPatronMarca = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txPatronModelo = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txPatronSerie = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblAdminPatrones = new javax.swing.JTable();
        txPatronFecha = new javax.swing.JTextField();
        codPatron = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mItemPuertosCom = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mItemSalir = new javax.swing.JMenuItem();
        mAdmin = new javax.swing.JMenu();
        menAdminOperador = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setSize(new java.awt.Dimension(1000, 744));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new java.awt.CardLayout());

        panInicioApriete.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Realizar aprietes");

        btnAprietesIniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAprietesIniciar.setForeground(new java.awt.Color(51, 51, 51));
        btnAprietesIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/icono_iniciar_Registro_sm.png"))); // NOI18N
        btnAprietesIniciar.setText("Iniciar aprietes");
        btnAprietesIniciar.setToolTipText("Guardar datos");
        btnAprietesIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprietesIniciarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fecha del sistema");

        txfAprietesFechaHora.setEditable(false);
        txfAprietesFechaHora.setBackground(new java.awt.Color(0, 204, 204));
        txfAprietesFechaHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("0");

        txfAprietesLinea1.setEditable(false);
        txfAprietesLinea1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txfAprietesLinea1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfAprietesLinea1.setText("0.00 PiesLibras");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txfAprietesFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txfAprietesLinea1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfAprietesFechaHora, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfAprietesLinea1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Orden de trabajo");

        txfAprietesODT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Cliente");

        txfAprietesCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnAprieteListarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/icono_buscar_sm.png"))); // NOI18N
        btnAprieteListarClientes.setToolTipText("Consultar clientes almacenados");
        btnAprieteListarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAprieteListarClientesMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Herramienta");

        cmbAprietesHerramientas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbAprietesHerramientas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAprietesHerramientasItemStateChanged(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Serie herramienta en calibración");

        txfAprietesDireccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Patron a utilizar");

        cmbAprietesPatron.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbAprietesPatron.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAprietesPatronItemStateChanged(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Dirección cliente");

        txfAprietesSerie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfAprietesODT)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txfAprietesCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAprieteListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbAprietesPatron, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfAprietesDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfAprietesSerie)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(cmbAprietesHerramientas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfAprietesODT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfAprietesSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfAprietesCliente)
                    .addComponent(btnAprieteListarClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfAprietesDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbAprietesHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAprietesPatron, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout pnAprietesGraficaLayout = new javax.swing.GroupLayout(pnAprietesGrafica);
        pnAprietesGrafica.setLayout(pnAprietesGraficaLayout);
        pnAprietesGraficaLayout.setHorizontalGroup(
            pnAprietesGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        pnAprietesGraficaLayout.setVerticalGroup(
            pnAprietesGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        tblAprietesAprietes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblAprietesAprietes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Apriete", "Medida", "+ EMP", "- EMP", "Medicion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAprietesAprietes.setRowHeight(30);
        tblAprietesAprietes.setSelectionBackground(new java.awt.Color(255, 153, 153));
        jScrollPane3.setViewportView(tblAprietesAprietes);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/icono_siguiente_apriete_sm.png"))); // NOI18N
        jButton2.setText("Siguiente apriete");
        jButton2.setToolTipText("Pasar al siguiente apriete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/icono_detener_sm.png"))); // NOI18N
        jButton3.setText("Detener apriete");
        jButton3.setToolTipText("Pasar al siguiente apriete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panInicioAprieteLayout = new javax.swing.GroupLayout(panInicioApriete);
        panInicioApriete.setLayout(panInicioAprieteLayout);
        panInicioAprieteLayout.setHorizontalGroup(
            panInicioAprieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInicioAprieteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInicioAprieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnAprietesGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInicioAprieteLayout.createSequentialGroup()
                        .addGroup(panInicioAprieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panInicioAprieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panInicioAprieteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAprietesIniciar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))))
                .addContainerGap())
        );
        panInicioAprieteLayout.setVerticalGroup(
            panInicioAprieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInicioAprieteLayout.createSequentialGroup()
                .addGroup(panInicioAprieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnAprietesIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInicioAprieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInicioAprieteLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnAprietesGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        scPanInicioApriete.setViewportView(panInicioApriete);

        panelPrincipal.add(scPanInicioApriete, "scPanInicioApriete");

        panInicioConsulta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Conusultar aprietes realizados");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Orden de trabajo");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Cliente");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Herramienta");

        txfAprieteODTConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cmbAprieteClienteConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbAprieteClienteConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbAprieteHerramietasConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbAprieteHerramietasConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblAprietesConsulta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblAprietesConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "Fecha", "ODT", "Herramienta", "Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAprietesConsulta.setRowHeight(35);
        tblAprietesConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAprietesConsultaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblAprietesConsulta);

        btnAprietesIniciar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAprietesIniciar1.setForeground(new java.awt.Color(51, 51, 51));
        btnAprietesIniciar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/icono_buscar_sm.png"))); // NOI18N
        btnAprietesIniciar1.setText("Buscar");
        btnAprietesIniciar1.setToolTipText("Buscar datos");
        btnAprietesIniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprietesIniciar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panInicioConsultaLayout = new javax.swing.GroupLayout(panInicioConsulta);
        panInicioConsulta.setLayout(panInicioConsultaLayout);
        panInicioConsultaLayout.setHorizontalGroup(
            panInicioConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInicioConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInicioConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addComponent(jScrollPane5)
                    .addGroup(panInicioConsultaLayout.createSequentialGroup()
                        .addGroup(panInicioConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txfAprieteODTConsulta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panInicioConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAprieteClienteConsulta, 0, 200, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panInicioConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(cmbAprieteHerramietasConsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panInicioConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnAprietesIniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panInicioConsultaLayout.setVerticalGroup(
            panInicioConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInicioConsultaLayout.createSequentialGroup()
                .addGroup(panInicioConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAprietesIniciar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInicioConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panInicioConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfAprieteODTConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAprieteClienteConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAprieteHerramietasConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );

        scPanInicioConsulta.setViewportView(panInicioConsulta);

        panelPrincipal.add(scPanInicioConsulta, "scPanInicioConsulta");

        panAdminOperador.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Administracion de operadores");

        btnOpGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpGuardar.setForeground(new java.awt.Color(51, 51, 51));
        btnOpGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/icono_guardar_sm.png"))); // NOI18N
        btnOpGuardar.setText("Guardar");
        btnOpGuardar.setToolTipText("Guardar datos");
        btnOpGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpGuardarActionPerformed(evt);
            }
        });

        btnOpNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpNuevo.setForeground(new java.awt.Color(51, 51, 51));
        btnOpNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/icono_limpiar_sm.png"))); // NOI18N
        btnOpNuevo.setText("Nuevo");
        btnOpNuevo.setToolTipText("Limpiar campos");
        btnOpNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpNuevoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 200));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/nuevo_usuario_lg.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Usuario");

        txfOpUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Contraseña");

        txfOpClave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Confirmar contraseña");

        txfOpConfClave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txfOpCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txfOpCodigo.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfOpClave)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfOpConfClave)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txfOpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfOpCodigo)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfOpUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txfOpCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfOpClave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfOpConfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nombre");

        txfOpNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Apellido");

        txfOpApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Documento");

        txfOpDocumento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        chkOpAdmin.setBackground(new java.awt.Color(255, 255, 255));
        chkOpAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkOpAdmin.setText("Es administrador");

        tblAdminOperadores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblAdminOperadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre y Apellidos", "Documento", "Es administrador", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdminOperadores.setRowHeight(35);
        tblAdminOperadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminOperadoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAdminOperadores);
        if (tblAdminOperadores.getColumnModel().getColumnCount() > 0) {
            tblAdminOperadores.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblAdminOperadores.getColumnModel().getColumn(1).setPreferredWidth(300);
            tblAdminOperadores.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblAdminOperadores.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblAdminOperadores.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        javax.swing.GroupLayout panAdminOperadorLayout = new javax.swing.GroupLayout(panAdminOperador);
        panAdminOperador.setLayout(panAdminOperadorLayout);
        panAdminOperadorLayout.setHorizontalGroup(
            panAdminOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAdminOperadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAdminOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(panAdminOperadorLayout.createSequentialGroup()
                        .addGroup(panAdminOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfOpNombre)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfOpApellido)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfOpDocumento)
                            .addComponent(chkOpAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panAdminOperadorLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panAdminOperadorLayout.setVerticalGroup(
            panAdminOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdminOperadorLayout.createSequentialGroup()
                .addGroup(panAdminOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnOpGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnOpNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panAdminOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAdminOperadorLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfOpNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfOpApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfOpDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkOpAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        scPanAdminOperador.setViewportView(panAdminOperador);

        panelPrincipal.add(scPanAdminOperador, "scPanAdminOperador");

        panAdminHerramienta.setBackground(new java.awt.Color(255, 255, 255));
        panAdminHerramienta.setPreferredSize(new java.awt.Dimension(941, 745));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Administracion de herramientas");

        btnOpNuevo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpNuevo2.setForeground(new java.awt.Color(51, 51, 51));
        btnOpNuevo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/icono_limpiar_sm.png"))); // NOI18N
        btnOpNuevo2.setText("Nuevo");
        btnOpNuevo2.setToolTipText("Limpiar campos");
        btnOpNuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpNuevo2ActionPerformed(evt);
            }
        });

        btnOpGuardar2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpGuardar2.setForeground(new java.awt.Color(51, 51, 51));
        btnOpGuardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/icono_guardar_sm.png"))); // NOI18N
        btnOpGuardar2.setText("Guardar");
        btnOpGuardar2.setToolTipText("Guardar datos");
        btnOpGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpGuardar2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Herramienta");

        txfHerrNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Numero serial");

        txfHerrSerial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Medida interna de herramienta");

        txfHerrMedida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txfHerrMedida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfHerrMedidaKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Medida externa de herramienta");

        txfHerrDiasFuera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txfHerrDiasFuera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfHerrDiasFueraKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Codigo");

        txfHerrDistrict.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Tipo de reporte");

        cmbHerrTpoReporte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfHerrNombre)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfHerrSerial)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txfHerrDistrict, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(txfHerrMedida, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfHerrDiasFuera)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(cmbHerrTpoReporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfHerrNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfHerrSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfHerrMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfHerrDiasFuera, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfHerrDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbHerrTpoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblHerrAprietes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Apriete", "Medida", "Valor EMP", "+ EMP", "- EMP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHerrAprietes.setRowHeight(35);
        tblHerrAprietes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHerrAprietesMouseClicked(evt);
            }
        });
        tblHerrAprietes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblHerrAprietesPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblHerrAprietes);
        if (tblHerrAprietes.getColumnModel().getColumnCount() > 0) {
            tblHerrAprietes.getColumnModel().getColumn(0).setMinWidth(55);
            tblHerrAprietes.getColumnModel().getColumn(0).setPreferredWidth(55);
            tblHerrAprietes.getColumnModel().getColumn(0).setMaxWidth(55);
            tblHerrAprietes.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblHerrAprietes.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblHerrAprietes.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblHerrAprietes.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblHerrAprietes.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        tblAdminHerramientas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblAdminHerramientas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Herramienta", "Nro serie", "Medida", "Dias fuera", "Distrito", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdminHerramientas.setRowHeight(35);
        tblAdminHerramientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminHerramientasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblAdminHerramientas);
        if (tblAdminHerramientas.getColumnModel().getColumnCount() > 0) {
            tblAdminHerramientas.getColumnModel().getColumn(0).setMinWidth(75);
            tblAdminHerramientas.getColumnModel().getColumn(0).setPreferredWidth(75);
            tblAdminHerramientas.getColumnModel().getColumn(0).setMaxWidth(75);
            tblAdminHerramientas.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblAdminHerramientas.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblAdminHerramientas.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblAdminHerramientas.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblAdminHerramientas.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        lbHerrCodigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout panAdminHerramientaLayout = new javax.swing.GroupLayout(panAdminHerramienta);
        panAdminHerramienta.setLayout(panAdminHerramientaLayout);
        panAdminHerramientaLayout.setHorizontalGroup(
            panAdminHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdminHerramientaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAdminHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAdminHerramientaLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAdminHerramientaLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbHerrCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpNuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE))
                .addContainerGap())
        );
        panAdminHerramientaLayout.setVerticalGroup(
            panAdminHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdminHerramientaLayout.createSequentialGroup()
                .addGroup(panAdminHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnOpGuardar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOpNuevo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHerrCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panAdminHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        scPanAdminHerramienta.setViewportView(panAdminHerramienta);

        panelPrincipal.add(scPanAdminHerramienta, "scPanAdminHerramienta");

        panAdminPatron.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Administracion de patrones");

        btnOpNuevo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpNuevo1.setForeground(new java.awt.Color(51, 51, 51));
        btnOpNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/icono_limpiar_sm.png"))); // NOI18N
        btnOpNuevo1.setText("Nuevo");
        btnOpNuevo1.setToolTipText("Limpiar campos");
        btnOpNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpNuevo1ActionPerformed(evt);
            }
        });

        btnOpGuardar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpGuardar1.setForeground(new java.awt.Color(51, 51, 51));
        btnOpGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/icono_guardar_sm.png"))); // NOI18N
        btnOpGuardar1.setText("Guardar");
        btnOpGuardar1.setToolTipText("Guardar datos");
        btnOpGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpGuardar1ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Nombre equipo");

        txPatronNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Marca");

        txPatronMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Modelo");

        txPatronModelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Serie");

        txPatronSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/iconos/icono_patron_lg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Fecha ultima calibración (AÑO/MES/DIA)");

        tblAdminPatrones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblAdminPatrones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Nombre", "Marca - Modelo", "Serie", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdminPatrones.setRowHeight(35);
        tblAdminPatrones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminPatronesMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblAdminPatrones);
        if (tblAdminPatrones.getColumnModel().getColumnCount() > 0) {
            tblAdminPatrones.getColumnModel().getColumn(0).setMinWidth(100);
            tblAdminPatrones.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblAdminPatrones.getColumnModel().getColumn(0).setMaxWidth(100);
            tblAdminPatrones.getColumnModel().getColumn(4).setMinWidth(125);
            tblAdminPatrones.getColumnModel().getColumn(4).setPreferredWidth(125);
            tblAdminPatrones.getColumnModel().getColumn(4).setMaxWidth(125);
        }

        txPatronFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        codPatron.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codPatron.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panAdminPatronLayout = new javax.swing.GroupLayout(panAdminPatron);
        panAdminPatron.setLayout(panAdminPatronLayout);
        panAdminPatronLayout.setHorizontalGroup(
            panAdminPatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdminPatronLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAdminPatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6)
                    .addGroup(panAdminPatronLayout.createSequentialGroup()
                        .addGroup(panAdminPatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txPatronNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txPatronMarca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txPatronModelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txPatronSerie, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txPatronFecha))
                        .addGap(18, 18, 18)
                        .addGroup(panAdminPatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAdminPatronLayout.createSequentialGroup()
                                .addComponent(codPatron, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOpNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOpGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );
        panAdminPatronLayout.setVerticalGroup(
            panAdminPatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdminPatronLayout.createSequentialGroup()
                .addGroup(panAdminPatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAdminPatronLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(codPatron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panAdminPatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOpGuardar1)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOpNuevo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(panAdminPatronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAdminPatronLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPatronNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPatronMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPatronModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPatronSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPatronFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        scPanAdminPatron.setViewportView(panAdminPatron);

        panelPrincipal.add(scPanAdminPatron, "scPanAdminPatron");

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("Aprietes");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Consultar aprietes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Realizar aprietes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        mItemPuertosCom.setText("Puertos COM");
        jMenu1.add(mItemPuertosCom);
        jMenu1.add(jSeparator3);

        mItemSalir.setText("Salir");
        mItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mItemSalir);

        jMenuBar1.add(jMenu1);

        mAdmin.setText("Administracion");
        mAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAdminActionPerformed(evt);
            }
        });

        menAdminOperador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menAdminOperador.setText("Administrar operador");
        menAdminOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAdminOperadorActionPerformed(evt);
            }
        });
        mAdmin.add(menAdminOperador);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Administrar herramienta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mAdmin.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Administrar patrones");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mAdmin.add(jMenuItem4);

        jMenuBar1.add(mAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAdminActionPerformed

    }//GEN-LAST:event_mAdminActionPerformed

    private void btnOpNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpNuevoActionPerformed
        this.contAdmin.limpiarCamposAdminOperador(txfOpNombre, txfOpApellido, txfOpDocumento, chkOpAdmin, txfOpUsuario, txfOpClave, txfOpConfClave, txfOpCodigo);
    }//GEN-LAST:event_btnOpNuevoActionPerformed

    private void btnOpGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpGuardarActionPerformed
        ArrayList<Usuario> listaOperadores = this.contAdmin.guardarOperador(txfOpNombre, txfOpApellido, txfOpDocumento, chkOpAdmin, txfOpUsuario, txfOpClave, txfOpConfClave, txfOpCodigo, tblAdminOperadores);
        if (listaOperadores != null && !listaOperadores.isEmpty()) {
            this.confApp.setListaOperadores(listaOperadores);
        }
    }//GEN-LAST:event_btnOpGuardarActionPerformed

    private void tblAdminOperadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminOperadoresMouseClicked
        int filaSeleccionada = tblAdminOperadores.rowAtPoint(evt.getPoint());
        int columnaSeleccionada = tblAdminOperadores.columnAtPoint(evt.getPoint());
        if (columnaSeleccionada < 4) {
            this.contAdmin.selecionarOperador(txfOpNombre, txfOpApellido, txfOpDocumento, chkOpAdmin, txfOpUsuario, txfOpClave, txfOpConfClave, txfOpCodigo, filaSeleccionada, columnaSeleccionada, this.confApp.getListaOperadores());
        } else {
            ArrayList<Usuario> listaOperadores = this.contAdmin.actualizarEstadoOperador(filaSeleccionada, columnaSeleccionada, this.confApp.getListaOperadores());
            if (listaOperadores != null && !listaOperadores.isEmpty()) {
                this.confApp.setListaOperadores(listaOperadores);
            }
        }
    }//GEN-LAST:event_tblAdminOperadoresMouseClicked

    private void mItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSalirActionPerformed
        this.confApp.validarSalidaSistema();
    }//GEN-LAST:event_mItemSalirActionPerformed

    private void menAdminOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAdminOperadorActionPerformed
        this.confApp.getContenedorPaneles().show(panelPrincipal, "scPanAdminOperador");
    }//GEN-LAST:event_menAdminOperadorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.confApp.getContenedorPaneles().show(panelPrincipal, "scPanInicioApriete");
        if (this.confApp.isRealizandoApriete() == false) {
            this.contAprietes.cargarHerramientas(cmbAprietesHerramientas, this.confApp.getHerramientas());
            this.contAprietes.cargarHerramientas(cmbAprieteHerramietasConsulta, this.confApp.getHerramientas());
            
            this.contAprietes.cargarPatrones(cmbAprietesPatron, this.confApp.getPatrones());
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.confApp.getContenedorPaneles().show(panelPrincipal, "scPanAdminHerramienta");
        this.contAdmin.cargarTiposDeReportesHerramientas(cmbHerrTpoReporte);
        this.contAdmin.limpiarCamposAdminHerramientas(lbHerrCodigo, txfHerrNombre, txfHerrSerial, txfHerrMedida, txfHerrDiasFuera, txfHerrDistrict, cmbHerrTpoReporte, tblHerrAprietes);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnOpNuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpNuevo2ActionPerformed
        this.contAdmin.limpiarCamposAdminHerramientas(lbHerrCodigo, txfHerrNombre, txfHerrSerial, txfHerrMedida, txfHerrDiasFuera, txfHerrDistrict, cmbHerrTpoReporte, tblHerrAprietes);
    }//GEN-LAST:event_btnOpNuevo2ActionPerformed

    private void btnOpGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpGuardar2ActionPerformed
        this.confApp.setHerramientas(this.contAdmin.guardarHerramienta(lbHerrCodigo, txfHerrNombre, txfHerrSerial, txfHerrMedida, txfHerrDiasFuera, txfHerrDistrict, cmbHerrTpoReporte, tblHerrAprietes, tblAdminHerramientas));
    }//GEN-LAST:event_btnOpGuardar2ActionPerformed

    private void tblHerrAprietesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHerrAprietesMouseClicked
        this.contAdmin.setFilaAprietes(tblHerrAprietes.rowAtPoint(evt.getPoint()));
        this.contAdmin.setColumnaAprietes(tblHerrAprietes.columnAtPoint(evt.getPoint()));
    }//GEN-LAST:event_tblHerrAprietesMouseClicked

    private void txfHerrMedidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfHerrMedidaKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && (caracter < '.' || caracter > '.' || String.valueOf(txfHerrMedida.getText()).contains(".")))
            evt.consume();
    }//GEN-LAST:event_txfHerrMedidaKeyTyped

    private void tblHerrAprietesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblHerrAprietesPropertyChange
        if (tblHerrAprietes != null && tblHerrAprietes.getModel() != null && tblHerrAprietes.getModel().getRowCount() > 0)
            this.contAdmin.actualizarCalculosAprietes(tblHerrAprietes);
    }//GEN-LAST:event_tblHerrAprietesPropertyChange

    private void txfHerrDiasFueraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfHerrDiasFueraKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && (caracter < '.' || caracter > '.' || String.valueOf(txfHerrDiasFuera.getText()).contains(".")))
            evt.consume();
    }//GEN-LAST:event_txfHerrDiasFueraKeyTyped

    private void tblAdminHerramientasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminHerramientasMouseClicked
        this.contAdmin.seleccionarHerramienta(lbHerrCodigo, txfHerrNombre, txfHerrSerial, txfHerrMedida, txfHerrDiasFuera, txfHerrDistrict, cmbHerrTpoReporte, tblHerrAprietes, tblAdminHerramientas, this.confApp.getHerramientas().get(tblAdminHerramientas.rowAtPoint(evt.getPoint())));
    }//GEN-LAST:event_tblAdminHerramientasMouseClicked

    private void cmbAprietesHerramientasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAprietesHerramientasItemStateChanged
        if (evt.getStateChange() == 2) {
            if (cmbAprietesHerramientas.getSelectedIndex() > 0) {
                this.confApp.setHerramientaActiva(this.confApp.getHerramientas().get(cmbAprietesHerramientas.getSelectedIndex() - 1));
                this.contAprietes.cargarAprietes(tblAprietesAprietes, this.confApp.getHerramientaActiva());
            } else {
                this.confApp.setHerramientaActiva(null);
            }
        }
    }//GEN-LAST:event_cmbAprietesHerramientasItemStateChanged

    private void btnAprietesIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprietesIniciarActionPerformed
        this.confApp.setPuertoCOM(this.conCOM.PUERTO_USO_COM);
        this.campActualizar.setCliente(txfAprietesCliente);
        this.campActualizar.setODT(txfAprietesODT);
        this.campActualizar.setHerramientas(cmbAprietesHerramientas);
        this.campActualizar.setTblAprietes(tblAprietesAprietes);
        
        this.campActualizar.setSerie(txfAprietesSerie);
        this.campActualizar.setDireccion(txfAprietesDireccion);
        this.campActualizar.setPatrones(cmbAprietesPatron);       
        
        this.campActualizar.setLinea1(txfAprietesLinea1);
        /*this.campActualizar.setLinea2(txfAprietesLinea2);
        this.campActualizar.setAuxiliar1(txfAprietesAuxiliar1);
        this.campActualizar.setAuxiliar2(txfAprietesAuxiliar2);*/
        this.campActualizar.setFechaHora(txfAprietesFechaHora);
        this.campActualizar.setPanelGrafica(pnAprietesGrafica);
        boolean actPuerto = this.confApp.activarPuertoCOM(this.campActualizar);
        if (actPuerto) {
            this.conCOM.pausarBuscadorDePuertos();
        }
    }//GEN-LAST:event_btnAprietesIniciarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.confApp.siguienteAprieteHerrmienta();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.confApp.getContenedorPaneles().show(panelPrincipal, "scPanInicioConsulta");
        this.contAprietes.listarClientes(cmbAprieteClienteConsulta);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnAprieteListarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAprieteListarClientesMouseClicked
        String ClienteSeleccionado = this.contAprietes.listarClientes(null);
        if (ClienteSeleccionado != null && !ClienteSeleccionado.equals("") && !ClienteSeleccionado.equals("SELECCIONE CLIENTE")){            
            txfAprietesCliente.setText(ClienteSeleccionado.split("\\|")[0].trim());
            txfAprietesDireccion.setText(ClienteSeleccionado.split("\\|")[1].trim());
            
        }
    }//GEN-LAST:event_btnAprieteListarClientesMouseClicked

    private void btnAprietesIniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprietesIniciar1ActionPerformed
        this.contAprietes.cargarResultadosBusqueda(tblAprietesConsulta, txfAprieteODTConsulta, cmbAprieteClienteConsulta, cmbAprieteHerramietasConsulta);
    }//GEN-LAST:event_btnAprietesIniciar1ActionPerformed

    private void tblAprietesConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAprietesConsultaMouseClicked
        if (evt.getClickCount() == 2 && tblAprietesConsulta.getSelectedRow() != -1) {
            reportePDF.ejecutarReporteHerramientaAjustada(String.valueOf(tblAprietesConsulta.getValueAt(tblAprietesConsulta.getSelectedRow(), 0)));
        }
    }//GEN-LAST:event_tblAprietesConsultaMouseClicked

    private void btnOpNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpNuevo1ActionPerformed
        this.contAdmin.limpiarCamposAdminPatron(codPatron, txPatronNombre, txPatronMarca, txPatronModelo, txPatronSerie, txPatronFecha);
    }//GEN-LAST:event_btnOpNuevo1ActionPerformed

    private void btnOpGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpGuardar1ActionPerformed
        this.confApp.setPatrones(this.contAdmin.guardarPatron(codPatron, txPatronNombre, txPatronMarca, txPatronModelo, txPatronSerie, txPatronFecha, tblAdminPatrones));
    }//GEN-LAST:event_btnOpGuardar1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (this.confApp.isRealizandoApriete() == false) {
            this.confApp.getContenedorPaneles().show(panelPrincipal, "scPanAdminPatron");
            this.contAdmin.limpiarCamposAdminPatron(codPatron, txPatronNombre, txPatronMarca, txPatronModelo, txPatronSerie, txPatronFecha);
            this.confApp.setPatrones(this.contAdmin.cargarPatrones(tblAdminPatrones));
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void tblAdminPatronesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminPatronesMouseClicked
        this.contAdmin.seleccionarPatron(codPatron, txPatronNombre, txPatronMarca, txPatronModelo, txPatronSerie, txPatronFecha, tblAdminPatrones, this.confApp.getPatrones().get(tblAdminPatrones.rowAtPoint(evt.getPoint())));
    }//GEN-LAST:event_tblAdminPatronesMouseClicked

    private void cmbAprietesPatronItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAprietesPatronItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAprietesPatronItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.confApp.detenerAprietes();
    }//GEN-LAST:event_jButton3ActionPerformed

    @Override
    public Image getIconImage() {
        return confAplicacion.cargarIconoAplicacion();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contenedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprieteListarClientes;
    private javax.swing.JButton btnAprietesIniciar;
    private javax.swing.JButton btnAprietesIniciar1;
    private javax.swing.JButton btnOpGuardar;
    private javax.swing.JButton btnOpGuardar1;
    private javax.swing.JButton btnOpGuardar2;
    private javax.swing.JButton btnOpNuevo;
    private javax.swing.JButton btnOpNuevo1;
    private javax.swing.JButton btnOpNuevo2;
    private javax.swing.JCheckBox chkOpAdmin;
    private javax.swing.JComboBox<String> cmbAprieteClienteConsulta;
    private javax.swing.JComboBox<String> cmbAprieteHerramietasConsulta;
    private javax.swing.JComboBox<String> cmbAprietesHerramientas;
    private javax.swing.JComboBox<String> cmbAprietesPatron;
    private javax.swing.JComboBox<String> cmbHerrTpoReporte;
    private javax.swing.JLabel codPatron;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbHerrCodigo;
    private javax.swing.JMenu mAdmin;
    private javax.swing.JMenu mItemPuertosCom;
    private javax.swing.JMenuItem mItemSalir;
    private javax.swing.JMenuItem menAdminOperador;
    private javax.swing.JPanel panAdminHerramienta;
    private javax.swing.JPanel panAdminOperador;
    private javax.swing.JPanel panAdminPatron;
    private javax.swing.JPanel panInicioApriete;
    private javax.swing.JPanel panInicioConsulta;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel pnAprietesGrafica;
    private javax.swing.JScrollPane scPanAdminHerramienta;
    private javax.swing.JScrollPane scPanAdminOperador;
    private javax.swing.JScrollPane scPanAdminPatron;
    private javax.swing.JScrollPane scPanInicioApriete;
    private javax.swing.JScrollPane scPanInicioConsulta;
    private javax.swing.JTable tblAdminHerramientas;
    private javax.swing.JTable tblAdminOperadores;
    private javax.swing.JTable tblAdminPatrones;
    private javax.swing.JTable tblAprietesAprietes;
    private javax.swing.JTable tblAprietesConsulta;
    private javax.swing.JTable tblHerrAprietes;
    private javax.swing.JTextField txPatronFecha;
    private javax.swing.JTextField txPatronMarca;
    private javax.swing.JTextField txPatronModelo;
    private javax.swing.JTextField txPatronNombre;
    private javax.swing.JTextField txPatronSerie;
    private javax.swing.JTextField txfAprieteODTConsulta;
    private javax.swing.JTextField txfAprietesCliente;
    private javax.swing.JTextField txfAprietesDireccion;
    private javax.swing.JTextField txfAprietesFechaHora;
    private javax.swing.JTextField txfAprietesLinea1;
    private javax.swing.JTextField txfAprietesODT;
    private javax.swing.JTextField txfAprietesSerie;
    private javax.swing.JTextField txfHerrDiasFuera;
    private javax.swing.JTextField txfHerrDistrict;
    private javax.swing.JTextField txfHerrMedida;
    private javax.swing.JTextField txfHerrNombre;
    private javax.swing.JTextField txfHerrSerial;
    private javax.swing.JTextField txfOpApellido;
    private javax.swing.JPasswordField txfOpClave;
    private javax.swing.JTextField txfOpCodigo;
    private javax.swing.JPasswordField txfOpConfClave;
    private javax.swing.JTextField txfOpDocumento;
    private javax.swing.JTextField txfOpNombre;
    private javax.swing.JTextField txfOpUsuario;
    // End of variables declaration//GEN-END:variables
}
